export const sponsorNames = [
    "Aberdeen Standard",
    "Akin Gump",
    "Alliance Bernstein",
    "Alvarez & Marsal",
    "Aon",
    "Appleseed Capital",
    "AQR",
    "AXA Investment Managers",
    "Baker McKenzie",
    "Brunswick Group",
    "Calvert Impact Capital",
    "University of Cambridge",
    "CenterPoint Energy",
    "Cleary Gottlieb",
    "Clorox",
    "Coca-Cola",
    "Darktrace",
    "Davies",
    "Deloitte",
    "Deutsche Bank",
    "Domini Impact Investments",
    "Dow Chemical",
    "Edelman",
    "EY",
    "Forcepoint",
    "Franklin Templeton",
    "FTI Consulting",
    "Global Cyber Security Center",
    "Georgeson",
    "Glass Lewis",
    "Grant & Eisenhofer",
    "Heuking Kuhn Luer Wojtek",
    "ICGN",
    "Israel Defense",
    "ISS Corporate Solutions",
    "Joele Frank",
    "Jones Day",
    "JP Morgan",
    "Kane Kessler",
    "KEKST CNC",
    "Kleinberg Kaplan",
    "KPMG",
    "Lazard Frere",
    "Lockheed Martin",
    "Macmillan",
    "MFS",
    "Microsoft",
    "MSCI",
    "Nasdaq",
    "Natixis",
    "Nestle Waters",
    "Norton Rose Fulbright",
    "Pfizer",
    "PWC",
    "SASB",
    "Schulte Roth & Zabel",
    "Sidley Austin",
    "Standard & Poor’s",
    "State Street Bank/SSGA",
    "Thomson Reuters",
    "Trillium Asset Management",
    "Wachtel Lipton Rosen & Katz"
]